apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pomoist-com-tls
spec:
  secretName: pomoist-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pomoist.com
  dnsNames:
    - pomoist.com
    - www.pomoist.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - pomoist.com
          - www.pomoist.com

